### ISSUE TITLE
Which client use to compile?

### ISSUE THREAD

**Issue by vk496** [majn/tgl#20]
Hi,

First, nice work with this fork. Very complete!

I'm trying to build `tg` with this library, but I don't find any repo for doing that (tried with @Cojad and @Rondoozle (the last seems more complete)), but any succes to make it work natively.

There are some way you use the library without `tg` client? Or there is a fork integrated with this library?

Salu2

**Comment by majn** [comment]
Why?

Do the fixed bugs affect tg too?

**Comment by vk496** [comment]
Yes. The API of Telegram updates very often, and `tgl` don't do it since 2014. 

I'm interested to port the command line client to Big Endian architectures, and would be nice start working from this library. 

Salu2

**Comment by BenWiederhake** [comment]
> `tgl` don't do it since 2014.

For completeness:  Vysheng last worked on it in 2016.  See [the `test` branch](https://github.com/vysheng/tgl/tree/test).  This fork is still more up-to-date than that.

What kind of problems did you encounter building tg with this fork?  We are not aware of any changed API, so it *should* be compatible, and delete-replacing the `tgl` folder *should* work.  We have no need for it though, and nobody tried it yet.

Help and pull requests for compatibility are very welcome.

**Comment by vk496** [comment]
As you mentioned, a simple replace should work. But not work for me (@vysheng test branch)

[https://gist.github.com/vk496/0ae9f063657a64a91f68b905d894b71e](url)

Will try to adapt.

Salu2

**Comment by vk496** [comment]
Sorry.

Seems that I used dirty build.

Clean clone and work like a charm

**Comment by BenWiederhake** [comment]
Thanks for clearing it up :+1:
