### ISSUE TITLE
How deal with code generation?

### ISSUE THREAD

**Issue by vk496** [majn/tgl#22]
Hi,

As I say some days ago, I'm trying to port the library to Big Endian archs.

At the moment, I succefully send [first packet](https://core.telegram.org/mtproto/samples-auth_key#1-request-for-p-q-authorization) and recieve it propperly.

However, I'm stuck on this func: [https://github.com/vk496/tgl/blob/endian/mtproto-common.h#L312](https://github.com/vk496/tgl/blob/endian/mtproto-common.h#L312).

The problem is that fetch int works great in sites like [this](https://github.com/vk496/tgl/blob/endian/mtproto-client.c#L210) but not work properly in some cases, like `auto-skip.c`

```C
int skip_type_res_p_q (struct paramed_type *T) {
  if (in_remaining () < 4) { return -1;}
  int magic = fetch_int ();
  switch (magic) {
  case 0x05162463: return skip_constructor_res_p_q (T);
  default: return -1;
  }
}
```

In the #21, @BenWiederhake said `it is viable to skip it and work on tgl directly`

What code generation really do? Should be always be skipable?

And... What do you think should I do with this endian problem? Create new function? Convert endian on magic bytes?

Salu2

**Comment by BenWiederhake** [comment]
I don't quite understand.  You say it works great with manually-written code, but have a problem with both generated and manually-written code?

In #21, I was talking about the programs `generate` and `tl-parse` themselves.  They essentially "only" generate the files in the folder `auto/`.  You could "skip" adapting/compiling/running these programs if you generate the files in the folder `auto/` on another machines and copy the files over (which you apparently already did).

The magic number comes from the definition of MTProto:

```
resPQ#05162463 nonce:int128 server_nonce:int128 pq:string server_public_key_fingerprints:(Vector long) = ResPQ;
```

And just to repeat: Good luck trying to port it. However, in my eyes, porting it to be endian-correct is neigh-impossible (what are you going to do about all those `write(…)` calls everywhere?). There may be more issues.

**Comment by vk496** [comment]
Sorry, I was confused about how was working that part of code (I was debugging a dirty build I think).

I thought that code generation could be skiped, but now I see that this is posible if you make "a trick".

About that `write(...)`... yes, is not eassy. But I have some time, a debugger and `qemu` for arch emulation 😃

My only problem is that I can't manage to cross-compile the software. Compiling on BigEndian emulated machine is soooo slow

Salu2

**Comment by BenWiederhake** [comment]
What issues did you have when cross-compiling?  [Cross-compiling to Windows](https://github.com/majn/telegram-purple/pull/397), isn't user-ready, but works.

**Comment by vk496** [comment]
I had troubles compiling the toolchain.

I think I solved that and currently I'm creating the packages for Arch.

Salu2
